version: 2
updates:
  - package-ecosystem: "npm" # use this yaml value when package manager is 'pnpm'
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "theopensystemslab/planx"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-istanbul"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"
    reviewers:
      - "theopensystemslab/planx"
