/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Email = string;
/**
 * Combined `PAO_START_NUMBER`, `PAO_START_SUFFIX`, `PAO_TEXT` OS LPI properties
 */
export type PrimaryAddressableObjectPAOStartRangeAndOrBuildingDescription =
  string;
/**
 * Combined `PAO_END_NUMBER`, `PAO_END_SUFFIX` OS LPI properties
 */
export type PrimaryAddressableObjectPAOEndRange = string;
/**
 * Combined `SAO_START_NUMBER`, `SAO_START_SUFFIX`, `SAO_TEXT` OS LPI properties
 */
export type SecondaryAddressableObjectSAOStartRangeAndOrBuildingDescription =
  string;
/**
 * Combined `SAO_END_NUMBER`, `SAO_END_SUFFIX` OS LPI properties
 */
export type SecondaryAddressableObjectSAOEndRange = string;
export type UniquePropertyReferenceNumber = string;
export type UniqueStreetReferenceNumber = string;
/**
 * Union of GeoJSON objects.
 */
export type GeoJSON =
  | Geometry
  | Feature3CGeometry2CGeoJsonProperties3E
  | FeatureCollection3CGeometry2CGeoJsonProperties3E;
/**
 * Geometry object. https://tools.ietf.org/html/rfc7946#section-3
 */
export type Geometry =
  | Point
  | MultiPoint
  | LineString
  | MultiLineString
  | Polygon
  | MultiPolygon
  | GeometryCollection;
/**
 * A Position is an array of coordinates. https://tools.ietf.org/html/rfc7946#section-3.1.1 Array should contain between two and three elements. The previous GeoJSON specification allowed more elements (e.g., which could be used to represent M values), but the current specification only allows X, Y, and (optionally) Z to be defined.
 *
 * Note: the type will not be narrowed down to `[number, number] | [number, number, number]` due to marginal benefits and the large impact of breaking change.
 *
 * See previous discussions on the type narrowing:
 * -  {@link  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21590 Nov 2017 }
 * -  {@link  https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67773 Dec 2023 }
 * -  {@link  https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71441 Dec 2024 }
 *
 * One can use a  {@link  https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates user-defined type guard that returns a type predicate }  to determine if a position is a 2D or 3D position.
 */
export type Position = number[];
/**
 * Name of the region sourced from planning.data.gov.uk/dataset/region; "London" is a proxy for the Greater London Authority
 */
export type Region =
  | "North East"
  | "North West"
  | "Yorkshire and The Humber"
  | "East Midlands"
  | "West Midlands"
  | "East of England"
  | "London"
  | "South East"
  | "South West";
/**
 * Property types derived from Basic Land and Property Unit (BLPU) classification codes
 */
export type PropertyType =
  | {
      description: "Commercial";
      value: "commercial";
    }
  | {
      description: "Agricultural";
      value: "commercial.agriculture";
    }
  | {
      description: "Farm / Non-Residential Associated Building";
      value: "commercial.agriculture.farm";
    }
  | {
      description: "Horticulture";
      value: "commercial.agriculture.horticulture";
    }
  | {
      description: "Vineyard";
      value: "commercial.agriculture.horticulture.vineyard";
    }
  | {
      description: "Watercress Bed";
      value: "commercial.agriculture.horticulture.watercress";
    }
  | {
      description: "Agricultural - Applicable to land in farm ownership and not run as a separate business enterprise";
      value: "commercial.agriculture.land";
    }
  | {
      description: "Permanent Crop / Crop Rotation";
      value: "commercial.agriculture.land.crops";
    }
  | {
      description: "Grazing Land";
      value: "commercial.agriculture.land.grazing";
    }
  | {
      description: "Orchard";
      value: "commercial.agriculture.land.orchard";
    }
  | {
      description: "Animal Centre";
      value: "commercial.animals";
    }
  | {
      description: "Equestrian";
      value: "commercial.animals.equestrian";
    }
  | {
      description: "Horse Racing / Breeding Stable";
      value: "commercial.animals.equestrian.racing";
    }
  | {
      description: "Commercial Stabling / Riding";
      value: "commercial.animals.equestrian.riding";
    }
  | {
      description: "Cattery / Kennel";
      value: "commercial.animals.kennelsCattery";
    }
  | {
      description: "Animal / Bird / Marine Sanctuary";
      value: "commercial.animals.sanctuary";
    }
  | {
      description: "Animal Sanctuary";
      value: "commercial.animals.sanctuary.animals";
    }
  | {
      description: "Marine Sanctuary";
      value: "commercial.animals.sanctuary.marine";
    }
  | {
      description: "Animal Services";
      value: "commercial.animals.services";
    }
  | {
      description: "Pet Grooming Salon";
      value: "commercial.animals.services.grooming";
    }
  | {
      description: "Animal Quarantining";
      value: "commercial.animals.services.quarantine";
    }
  | {
      description: "Vet / Animal Medical Treatment";
      value: "commercial.animals.vet";
    }
  | {
      description: "Community Services";
      value: "commercial.community";
    }
  | {
      description: "Public Household Waste Recycling Centre (HWRC)";
      value: "commercial.community.HWRC";
    }
  | {
      description: "Cemetery / Crematorium / Graveyard. In Current Use.";
      value: "commercial.community.cemetery";
    }
  | {
      description: "Cemetery";
      value: "commercial.community.cemetery.cemetery";
    }
  | {
      description: "Chapel Of Rest";
      value: "commercial.community.cemetery.chapelOfRest";
    }
  | {
      description: "Columbarium";
      value: "commercial.community.cemetery.columbarium";
    }
  | {
      description: "Crematorium";
      value: "commercial.community.cemetery.crematorium";
    }
  | {
      description: "Military Cemetery";
      value: "commercial.community.cemetery.military";
    }
  | {
      description: "Law Court";
      value: "commercial.community.court";
    }
  | {
      description: "Job Centre";
      value: "commercial.community.employment";
    }
  | {
      description: "Public / Village Hall / Other Community Facility";
      value: "commercial.community.hall";
    }
  | {
      description: "Youth Recreational / Social Club";
      value: "commercial.community.hall.club";
    }
  | {
      description: "Prison";
      value: "commercial.community.prison";
    }
  | {
      description: "HM Detention Centre";
      value: "commercial.community.prison.detention";
    }
  | {
      description: "Secure Residential Accommodation";
      value: "commercial.community.prison.secureResidential";
    }
  | {
      description: "HM Prison Service";
      value: "commercial.community.prison.service";
    }
  | {
      description: "Recycling Site";
      value: "commercial.community.recycling";
    }
  | {
      description: "Church Hall / Religious Meeting Place / Hall";
      value: "commercial.community.religious";
    }
  | {
      description: "Scout hut";
      value: "commercial.community.scoutHut";
    }
  | {
      description: "Community Service Centre / Office";
      value: "commercial.community.services";
    }
  | {
      description: "Public Convenience";
      value: "commercial.community.wc";
    }
  | {
      description: "Education";
      value: "commercial.education";
    }
  | {
      description: "College";
      value: "commercial.education.college";
    }
  | {
      description: "Further Education";
      value: "commercial.education.college.further";
    }
  | {
      description: "Higher Education";
      value: "commercial.education.college.higher";
    }
  | {
      description: "Children’s Nursery / Crèche";
      value: "commercial.education.nursery";
    }
  | {
      description: "Other Educational Establishment";
      value: "commercial.education.other";
    }
  | {
      description: "Preparatory / First / Primary / Infant / Junior / Middle School";
      value: "commercial.education.school";
    }
  | {
      description: "Boarding School";
      value: "commercial.education.school.boarding";
    }
  | {
      description: "First School";
      value: "commercial.education.school.first";
    }
  | {
      description: "Infant School";
      value: "commercial.education.school.infant";
    }
  | {
      description: "Junior School";
      value: "commercial.education.school.junior";
    }
  | {
      description: "Middle School";
      value: "commercial.education.school.middle";
    }
  | {
      description: "Non State Primary / Preparatory School";
      value: "commercial.education.school.primary.private";
    }
  | {
      description: "Primary School";
      value: "commercial.education.school.primary.state";
    }
  | {
      description: "Secondary / High School";
      value: "commercial.education.school.secondary";
    }
  | {
      description: "Non State Secondary School";
      value: "commercial.education.school.secondary.private";
    }
  | {
      description: "Secondary School";
      value: "commercial.education.school.secondary.state";
    }
  | {
      description: "Special Needs Establishment";
      value: "commercial.education.specialNeeds";
    }
  | {
      description: "Training Centre";
      value: "commercial.education.trainingCentre";
    }
  | {
      description: "University";
      value: "commercial.education.university";
    }
  | {
      description: "Emergency / Rescue Service";
      value: "commercial.emergency";
    }
  | {
      description: "Air Sea Rescue / Air Ambulance";
      value: "commercial.emergency.air";
    }
  | {
      description: "Ambulance Station";
      value: "commercial.emergency.ambulance";
    }
  | {
      description: "Coastguard Rescue / Lookout / Station";
      value: "commercial.emergency.coastguard";
    }
  | {
      description: "Fire command centre";
      value: "commercial.emergency.fireCommandCentre";
    }
  | {
      description: "Fire Station";
      value: "commercial.emergency.fireStation";
    }
  | {
      description: "Fire Service Training";
      value: "commercial.emergency.fireTraining";
    }
  | {
      description: "Lifeboat Services / Station";
      value: "commercial.emergency.lifeboat";
    }
  | {
      description: "Lifeguard Facility";
      value: "commercial.emergency.lifeguard";
    }
  | {
      description: "Lighthouse";
      value: "commercial.emergency.lighthouse";
    }
  | {
      description: "Mountain Rescue Station";
      value: "commercial.emergency.mountain";
    }
  | {
      description: "Police Box / Kiosk";
      value: "commercial.emergency.policeBox";
    }
  | {
      description: "Police / Transport Police / Station";
      value: "commercial.emergency.policeStation";
    }
  | {
      description: "Police Training";
      value: "commercial.emergency.policeTraining";
    }
  | {
      description: "Fishery";
      value: "commercial.fish";
    }
  | {
      description: "Fish Farming";
      value: "commercial.fish.farm";
    }
  | {
      description: "Fish Hatchery";
      value: "commercial.fish.hatchery";
    }
  | {
      description: "Oyster / Mussel Bed";
      value: "commercial.fish.oysters";
    }
  | {
      description: "Hotel / Motel / Boarding / Guest House";
      value: "commercial.guest";
    }
  | {
      description: "Boarding / Guest House / Bed And Breakfast / Youth Hostel";
      value: "commercial.guest.hostel";
    }
  | {
      description: "Youth Hostel";
      value: "commercial.guest.hostel.youth";
    }
  | {
      description: "Hotel/Motel";
      value: "commercial.guest.hotel";
    }
  | {
      description: "Holiday Let/Accomodation/Short-Term Let Other Than CH01";
      value: "commercial.guest.shortLet";
    }
  | {
      description: "Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites";
      value: "commercial.industrial";
    }
  | {
      description: "Slaughter House / Abattoir";
      value: "commercial.industrial.abattoir";
    }
  | {
      description: "Builders’ Yard";
      value: "commercial.industrial.buildersYard";
    }
  | {
      description: "Coke works and other coal carbonisation plants";
      value: "commercial.industrial.carbonisation";
    }
  | {
      description: "Mineral / Ore Working / Quarry / Mine";
      value: "commercial.industrial.extraction";
    }
  | {
      description: "Mineral Distribution / Storage";
      value: "commercial.industrial.extraction.distribution";
    }
  | {
      description: "Mineral Mining / Active";
      value: "commercial.industrial.extraction.mining";
    }
  | {
      description: "Oil / Gas Extraction / Active";
      value: "commercial.industrial.extraction.oilGas";
    }
  | {
      description: "Mineral Processing";
      value: "commercial.industrial.extraction.processing";
    }
  | {
      description: "Mineral Quarrying / Open Extraction / Active";
      value: "commercial.industrial.extraction.quarrying";
    }
  | {
      description: "Sand and gravel working";
      value: "commercial.industrial.extraction.quarrying.sandOrGravel";
    }
  | {
      description: "Film and photographic processing works";
      value: "commercial.industrial.filmProcessing";
    }
  | {
      description: "Fish Processing";
      value: "commercial.industrial.fishProcessing";
    }
  | {
      description: "Incinerator / Waste Transfer Station";
      value: "commercial.industrial.incineration";
    }
  | {
      description: "Industrial laundry";
      value: "commercial.industrial.laundry";
    }
  | {
      description: "Workshop / Light Industrial";
      value: "commercial.industrial.light";
    }
  | {
      description: "Catering premises & production";
      value: "commercial.industrial.light.catering";
    }
  | {
      description: "Servicing Garage";
      value: "commercial.industrial.light.garage";
    }
  | {
      description: "Postal Sorting / Distribution";
      value: "commercial.industrial.light.storage.post";
    }
  | {
      description: "Maintenance Depot";
      value: "commercial.industrial.maintenanceDepot";
    }
  | {
      description: "Factory/Manufacturing";
      value: "commercial.industrial.manufacturing";
    }
  | {
      description: "Aircraft Works";
      value: "commercial.industrial.manufacturing.aircraft";
    }
  | {
      description: "Brewery";
      value: "commercial.industrial.manufacturing.beer";
    }
  | {
      description: "Boat Building";
      value: "commercial.industrial.manufacturing.boats";
    }
  | {
      description: "Brick Works";
      value: "commercial.industrial.manufacturing.bricks";
    }
  | {
      description: "Cement Works";
      value: "commercial.industrial.manufacturing.cement";
    }
  | {
      description: "Chemical Works";
      value: "commercial.industrial.manufacturing.chemicals";
    }
  | {
      description: "Cider Manufacture";
      value: "commercial.industrial.manufacturing.cider";
    }
  | {
      description: "Dairy Processing";
      value: "commercial.industrial.manufacturing.dairy";
    }
  | {
      description: "Distillery";
      value: "commercial.industrial.manufacturing.distillery";
    }
  | {
      description: "Dye works";
      value: "commercial.industrial.manufacturing.dyeWorks";
    }
  | {
      description: "Engineering works";
      value: "commercial.industrial.manufacturing.engineering";
    }
  | {
      description: "Flour Mill";
      value: "commercial.industrial.manufacturing.flour";
    }
  | {
      description: "Food Processing";
      value: "commercial.industrial.manufacturing.food";
    }
  | {
      description: "Glassworks";
      value: "commercial.industrial.manufacturing.glass";
    }
  | {
      description: "Oast House";
      value: "commercial.industrial.manufacturing.hops";
    }
  | {
      description: "Metal manufacturing & processing";
      value: "commercial.industrial.manufacturing.metal";
    }
  | {
      description: "Oil Refining";
      value: "commercial.industrial.manufacturing.oil";
    }
  | {
      description: "Ordnance manufacturing & processing";
      value: "commercial.industrial.manufacturing.ordnance";
    }
  | {
      description: "Manufacturing";
      value: "commercial.industrial.manufacturing.other";
    }
  | {
      description: "Paper Mill";
      value: "commercial.industrial.manufacturing.paper";
    }
  | {
      description: "Pottery Manufacturing";
      value: "commercial.industrial.manufacturing.pottery";
    }
  | {
      description: "Printing Works";
      value: "commercial.industrial.manufacturing.printing";
    }
  | {
      description: "Shipyard";
      value: "commercial.industrial.manufacturing.ships";
    }
  | {
      description: "Steel Works";
      value: "commercial.industrial.manufacturing.steel";
    }
  | {
      description: "Sugar Refinery";
      value: "commercial.industrial.manufacturing.sugar";
    }
  | {
      description: "Textile works";
      value: "commercial.industrial.manufacturing.textileWorks";
    }
  | {
      description: "Timber Mill";
      value: "commercial.industrial.manufacturing.timber";
    }
  | {
      description: "Winery";
      value: "commercial.industrial.manufacturing.wine";
    }
  | {
      description: "Recycling Plant";
      value: "commercial.industrial.recycling";
    }
  | {
      description: "Leisure - Applicable to recreational sites and enterprises";
      value: "commercial.leisure";
    }
  | {
      description: "Amusements";
      value: "commercial.leisure.amusements";
    }
  | {
      description: "Leisure Pier";
      value: "commercial.leisure.amusements.pier";
    }
  | {
      description: "Arena / Stadium";
      value: "commercial.leisure.arena";
    }
  | {
      description: "Showground";
      value: "commercial.leisure.arena.showground";
    }
  | {
      description: "Stadium";
      value: "commercial.leisure.arena.stadium";
    }
  | {
      description: "Beach Hut (Recreational, Non-Residential Use Only)";
      value: "commercial.leisure.beachHut";
    }
  | {
      description: "Casino";
      value: "commercial.leisure.casino";
    }
  | {
      description: "Licensed Private Members’ Club";
      value: "commercial.leisure.club.private";
    }
  | {
      description: "Recreational / Social Club";
      value: "commercial.leisure.club.social";
    }
  | {
      description: "Dancehall";
      value: "commercial.leisure.dancehall";
    }
  | {
      description: "Bingo Hall / Cinema / Conference / Exhibition Centre / Theatre / Concert Hall";
      value: "commercial.leisure.entertainment";
    }
  | {
      description: "Cinema";
      value: "commercial.leisure.entertainment.cinema";
    }
  | {
      description: "Concert Hall";
      value: "commercial.leisure.entertainment.concert";
    }
  | {
      description: "Conference / Exhibition Centre";
      value: "commercial.leisure.entertainment.exhibition";
    }
  | {
      description: "Entertainment Complex";
      value: "commercial.leisure.entertainment.mixed";
    }
  | {
      description: "Theatre";
      value: "commercial.leisure.entertainment.theatre";
    }
  | {
      description: "Holiday / Campsite";
      value: "commercial.leisure.holiday";
    }
  | {
      description: "Holiday Accommodation";
      value: "commercial.leisure.holiday.accommodation";
    }
  | {
      description: "Camping";
      value: "commercial.leisure.holiday.camping";
    }
  | {
      description: "Caravanning";
      value: "commercial.leisure.holiday.caravanning";
    }
  | {
      description: "Holiday Centre";
      value: "commercial.leisure.holiday.centre";
    }
  | {
      description: "Holiday home site";
      value: "commercial.leisure.holiday.holidayHomeSite";
    }
  | {
      description: "Youth Organisation Camp";
      value: "commercial.leisure.holiday.youth";
    }
  | {
      description: "Ice skating rink";
      value: "commercial.leisure.iceSkating";
    }
  | {
      description: "Library";
      value: "commercial.leisure.library";
    }
  | {
      description: "Reading Room";
      value: "commercial.leisure.library.readingRoom";
    }
  | {
      description: "Museum / Gallery";
      value: "commercial.leisure.museum";
    }
  | {
      description: "Art Centre / Gallery";
      value: "commercial.leisure.museum.art";
    }
  | {
      description: "Aviation Museum";
      value: "commercial.leisure.museum.aviation";
    }
  | {
      description: "Heritage Centre";
      value: "commercial.leisure.museum.heritage";
    }
  | {
      description: "Historic Vessel / Aircraft / Vehicle";
      value: "commercial.leisure.museum.historicVehicles";
    }
  | {
      description: "Industrial Museum";
      value: "commercial.leisure.museum.industrial";
    }
  | {
      description: "Maritime Museum";
      value: "commercial.leisure.museum.maritime";
    }
  | {
      description: "Military Museum";
      value: "commercial.leisure.museum.military";
    }
  | {
      description: "Science Museum";
      value: "commercial.leisure.museum.science";
    }
  | {
      description: "Transport Museum";
      value: "commercial.leisure.museum.transport";
    }
  | {
      description: "Amusement Park";
      value: "commercial.leisure.park.amusement";
    }
  | {
      description: "Aquatic Attraction";
      value: "commercial.leisure.park.aquatic";
    }
  | {
      description: "Model Village Site";
      value: "commercial.leisure.park.model";
    }
  | {
      description: "Wildlife / Zoological Park";
      value: "commercial.leisure.park.wildlife";
    }
  | {
      description: "Zoo / Theme Park";
      value: "commercial.leisure.park.zoo";
    }
  | {
      description: "Petting farm";
      value: "commercial.leisure.pettingFarm";
    }
  | {
      description: "Indoor / Outdoor Leisure / Sporting Activity / Centre";
      value: "commercial.leisure.sport";
    }
  | {
      description: "Athletics Facility";
      value: "commercial.leisure.sport.athletics";
    }
  | {
      description: "Bowls Facility";
      value: "commercial.leisure.sport.bowls";
    }
  | {
      description: "Activity / Leisure / Sports Centre";
      value: "commercial.leisure.sport.centre";
    }
  | {
      description: "Cricket Facility";
      value: "commercial.leisure.sport.cricket";
    }
  | {
      description: "Curling Facility";
      value: "commercial.leisure.sport.curling";
    }
  | {
      description: "Cycling Sports Facility";
      value: "commercial.leisure.sport.cycling";
    }
  | {
      description: "Dance studio";
      value: "commercial.leisure.sport.dance";
    }
  | {
      description: "Greyhound Racing Facility";
      value: "commercial.leisure.sport.dogracing";
    }
  | {
      description: "Equestrian Sports Facility";
      value: "commercial.leisure.sport.equestrian";
    }
  | {
      description: "Civilian Firing Facility";
      value: "commercial.leisure.sport.firing";
    }
  | {
      description: "Fishing / Angling Facility";
      value: "commercial.leisure.sport.fishing";
    }
  | {
      description: "Football Facility";
      value: "commercial.leisure.sport.football";
    }
  | {
      description: "Gliding Facility";
      value: "commercial.leisure.sport.gliding";
    }
  | {
      description: "Golf Facility";
      value: "commercial.leisure.sport.golf";
    }
  | {
      description: "Hockey Facility";
      value: "commercial.leisure.sport.hockey";
    }
  | {
      description: "Horse Racing Facility";
      value: "commercial.leisure.sport.horseracing";
    }
  | {
      description: "Model Sports Facility";
      value: "commercial.leisure.sport.model";
    }
  | {
      description: "Motor Sports Facility";
      value: "commercial.leisure.sport.motor";
    }
  | {
      description: "Playing Field";
      value: "commercial.leisure.sport.playingField";
    }
  | {
      description: "Racquet Sports Facility";
      value: "commercial.leisure.sport.racquet";
    }
  | {
      description: "Recreation Ground";
      value: "commercial.leisure.sport.recreationGround";
    }
  | {
      description: "Rugby Facility";
      value: "commercial.leisure.sport.rugby";
    }
  | {
      description: "Shinty Facility";
      value: "commercial.leisure.sport.shinty";
    }
  | {
      description: "Skateboarding Facility";
      value: "commercial.leisure.sport.skateboarding";
    }
  | {
      description: "Diving / Swimming Facility";
      value: "commercial.leisure.sport.swimming";
    }
  | {
      description: "Public Tennis Court";
      value: "commercial.leisure.sport.tennis";
    }
  | {
      description: "Tenpin Bowling Facility";
      value: "commercial.leisure.sport.tenpin";
    }
  | {
      description: "Water Sports Facility";
      value: "commercial.leisure.sport.water";
    }
  | {
      description: "Wildlife Sports Facility";
      value: "commercial.leisure.sport.wildlife";
    }
  | {
      description: "Winter Sports Facility";
      value: "commercial.leisure.sport.winter";
    }
  | {
      description: "Medical";
      value: "commercial.medical";
    }
  | {
      description: "General Practice Surgery / Clinic";
      value: "commercial.medical.GP";
    }
  | {
      description: "Assessment / Development Services";
      value: "commercial.medical.assessment";
    }
  | {
      description: "Medical care";
      value: "commercial.medical.care";
    }
  | {
      description: "Care home/Hospice";
      value: "commercial.medical.careHome";
    }
  | {
      description: "Dentist";
      value: "commercial.medical.dentist";
    }
  | {
      description: "Health Centre";
      value: "commercial.medical.healthCentre";
    }
  | {
      description: "Health Care Services";
      value: "commercial.medical.healthServices";
    }
  | {
      description: "Hospital";
      value: "commercial.medical.hospital";
    }
  | {
      description: "Medical / Testing / Research Laboratory";
      value: "commercial.medical.lab";
    }
  | {
      description: "Professional Medical Service";
      value: "commercial.medical.professional";
    }
  | {
      description: "Office";
      value: "commercial.office";
    }
  | {
      description: "Broadcasting (TV / Radio)";
      value: "commercial.office.broadcasting";
    }
  | {
      description: "Office / Work Studio";
      value: "commercial.office.workspace";
    }
  | {
      description: "Embassy /, High Commission / Consulate";
      value: "commercial.office.workspace.embassy";
    }
  | {
      description: "Film Studio";
      value: "commercial.office.workspace.film";
    }
  | {
      description: "Local Government Service";
      value: "commercial.office.workspace.gov.local";
    }
  | {
      description: "Central Government Service";
      value: "commercial.office.workspace.gov.national";
    }
  | {
      description: "Retail";
      value: "commercial.retail";
    }
  | {
      description: "Barber / Hairdresser / Beauty Salon / Tattoo Parlour";
      value: "commercial.retail.beauty";
    }
  | {
      description: "Betting Office";
      value: "commercial.retail.bettingOffice";
    }
  | {
      description: "Public House / Bar / Nightclub";
      value: "commercial.retail.drinking";
    }
  | {
      description: "Dry cleaner";
      value: "commercial.retail.dryCleaner";
    }
  | {
      description: "Bank / Financial Service";
      value: "commercial.retail.financial";
    }
  | {
      description: "Petrol Filling Station";
      value: "commercial.retail.fuel";
    }
  | {
      description: "Laundrette";
      value: "commercial.retail.laundrette";
    }
  | {
      description: "Other Licensed Premise / Vendor";
      value: "commercial.retail.licensedPremises";
    }
  | {
      description: "Local shop";
      value: "commercial.retail.localShop";
    }
  | {
      description: "Market (Indoor / Outdoor)";
      value: "commercial.retail.market";
    }
  | {
      description: "Fish Market";
      value: "commercial.retail.market.fish";
    }
  | {
      description: "Fruit / Vegetable Market";
      value: "commercial.retail.market.fruit";
    }
  | {
      description: "Livestock Market";
      value: "commercial.retail.market.livestock";
    }
  | {
      description: "Pay day loan shop";
      value: "commercial.retail.payDayLoanShop";
    }
  | {
      description: "Post Office";
      value: "commercial.retail.post";
    }
  | {
      description: "Restaurant / Cafeteria";
      value: "commercial.retail.restaurant";
    }
  | {
      description: "Retail Service Agent";
      value: "commercial.retail.services";
    }
  | {
      description: "Shop";
      value: "commercial.retail.shop";
    }
  | {
      description: "Garden Centre";
      value: "commercial.retail.shop.gardenCentre";
    }
  | {
      description: "Showroom";
      value: "commercial.retail.showroom";
    }
  | {
      description: "Fast Food Outlet / Takeaway (Hot / Cold)";
      value: "commercial.retail.takeaway";
    }
  | {
      description: "Visitor Information";
      value: "commercial.retail.visitorInformation";
    }
  | {
      description: "Audio recording studio";
      value: "commercial.services.audioStudio";
    }
  | {
      description: "Childminding";
      value: "commercial.services.childminding";
    }
  | {
      description: "Photographic studio";
      value: "commercial.services.photographicStudio";
    }
  | {
      description: "Warehouse / Store / Storage Depot";
      value: "commercial.storage";
    }
  | {
      description: "Crop Handling / Storage";
      value: "commercial.storage.crops";
    }
  | {
      description: "Wholesale Distribution";
      value: "commercial.storage.distribution";
    }
  | {
      description: "Solid Fuel Distribution";
      value: "commercial.storage.distribution.solidFuel";
    }
  | {
      description: "Timber Distribution";
      value: "commercial.storage.distribution.timber";
    }
  | {
      description: "Hydrocarbon storage";
      value: "commercial.storage.hydrocarbon";
    }
  | {
      description: "Storage Land";
      value: "commercial.storage.land";
    }
  | {
      description: "General Storage Land";
      value: "commercial.storage.land.general";
    }
  | {
      description: "Retail Warehouse";
      value: "commercial.storage.retail";
    }
  | {
      description: "Solid Fuel Storage";
      value: "commercial.storage.solidFuel";
    }
  | {
      description: "Timber Storage";
      value: "commercial.storage.timber";
    }
  | {
      description: "Vehicle Storage";
      value: "commercial.storage.transport";
    }
  | {
      description: "Boat Storage";
      value: "commercial.storage.transport.boat";
    }
  | {
      description: "Bus / Coach Depot";
      value: "commercial.storage.transport.bus";
    }
  | {
      description: "Transport";
      value: "commercial.transport";
    }
  | {
      description: "Airfield / Airstrip / Airport / Air Transport Infrastructure Facility";
      value: "commercial.transport.air";
    }
  | {
      description: "Airfield";
      value: "commercial.transport.air.airfield";
    }
  | {
      description: "Airport";
      value: "commercial.transport.air.airport";
    }
  | {
      description: "Helicopter Station";
      value: "commercial.transport.air.helicopterStation";
    }
  | {
      description: "Heliport / Helipad";
      value: "commercial.transport.air.heliport";
    }
  | {
      description: "Air Transport Infrastructure Services";
      value: "commercial.transport.air.infrastructure";
    }
  | {
      description: "Air Passenger Terminal";
      value: "commercial.transport.air.passengerTerminal";
    }
  | {
      description: "Goods Freight Handling / Terminal";
      value: "commercial.transport.freight";
    }
  | {
      description: "Air Freight Terminal";
      value: "commercial.transport.freight.air";
    }
  | {
      description: "Container Freight";
      value: "commercial.transport.freight.container";
    }
  | {
      description: "Rail Freight Transport";
      value: "commercial.transport.freight.rail";
    }
  | {
      description: "Road Freight Transport";
      value: "commercial.transport.freight.road";
    }
  | {
      description: "Transport Related Infrastructure";
      value: "commercial.transport.infrastructure";
    }
  | {
      description: "Monorail";
      value: "commercial.transport.rail.monorail";
    }
  | {
      description: "Railway Asset";
      value: "commercial.transport.rail.railAsset";
    }
  | {
      description: "Train station";
      value: "commercial.transport.rail.terminal";
    }
  | {
      description: "Transport Track / Railway";
      value: "commercial.transport.rail.track";
    }
  | {
      description: "Bus Shelter";
      value: "commercial.transport.road.bus";
    }
  | {
      description: "Weighbridge / Load Gauge";
      value: "commercial.transport.road.infrastructure.weighing";
    }
  | {
      description: "Overnight Lorry Park";
      value: "commercial.transport.road.overnightLorryPark";
    }
  | {
      description: "Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site";
      value: "commercial.transport.road.parking";
    }
  | {
      description: "Public Car Parking";
      value: "commercial.transport.road.parking.car";
    }
  | {
      description: "Public Coach Parking";
      value: "commercial.transport.road.parking.coach";
    }
  | {
      description: "Public Commercial Vehicle Parking";
      value: "commercial.transport.road.parking.commercialVehicle";
    }
  | {
      description: "Public Park And Ride";
      value: "commercial.transport.road.parking.parkAndRide";
    }
  | {
      description: "Bus station";
      value: "commercial.transport.road.terminal.bus";
    }
  | {
      description: "Station / Interchange / Terminal / Halt";
      value: "commercial.transport.terminal";
    }
  | {
      description: "Chair Lift / Cable Car / Ski Tow";
      value: "commercial.transport.track.cable";
    }
  | {
      description: "Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay";
      value: "commercial.transport.water.dock";
    }
  | {
      description: "Passenger Ferry Terminal";
      value: "commercial.transport.water.dock.ferry.passengers";
    }
  | {
      description: "Vehicular Ferry Terminal";
      value: "commercial.transport.water.dock.ferry.vehicles";
    }
  | {
      description: "Non-Tanker Nautical Berthing";
      value: "commercial.transport.water.dock.generalBerth";
    }
  | {
      description: "Ship Passenger Terminal";
      value: "commercial.transport.water.dock.passenger";
    }
  | {
      description: "Nautical Refuelling Facility";
      value: "commercial.transport.water.dock.refuelling";
    }
  | {
      description: "Slipway";
      value: "commercial.transport.water.dock.slipway";
    }
  | {
      description: "Tanker Berthing";
      value: "commercial.transport.water.dock.tankerBerth";
    }
  | {
      description: "Aqueduct";
      value: "commercial.transport.water.infrastructure.aqueduct";
    }
  | {
      description: "Lock";
      value: "commercial.transport.water.infrastructure.lock";
    }
  | {
      description: "Weir";
      value: "commercial.transport.water.infrastructure.weir";
    }
  | {
      description: "Marina";
      value: "commercial.transport.water.marina";
    }
  | {
      description: "Mooring";
      value: "commercial.transport.water.mooring";
    }
  | {
      description: "Utility";
      value: "commercial.utility";
    }
  | {
      description: "CCTV";
      value: "commercial.utility.CCTV";
    }
  | {
      description: "Automated Teller Machine (ATM)";
      value: "commercial.utility.atm";
    }
  | {
      description: "Dam";
      value: "commercial.utility.dam";
    }
  | {
      description: "Power Station / Energy Production";
      value: "commercial.utility.electricity";
    }
  | {
      description: "Electricity Distribution Facility";
      value: "commercial.utility.electricity.distribution";
    }
  | {
      description: "Electricity Production Facility";
      value: "commercial.utility.electricity.production";
    }
  | {
      description: "Solar farms";
      value: "commercial.utility.electricity.solarFarm";
    }
  | {
      description: "Electricity Sub-Station";
      value: "commercial.utility.electricity.substation";
    }
  | {
      description: "Wind Farm";
      value: "commercial.utility.electricity.windFarm";
    }
  | {
      description: "Wind Turbine";
      value: "commercial.utility.electricity.windTurbine";
    }
  | {
      description: "Landfill";
      value: "commercial.utility.landfill";
    }
  | {
      description: "Gas / Oil Storage / Distribution";
      value: "commercial.utility.oilGas";
    }
  | {
      description: "Gas Governor";
      value: "commercial.utility.oilGas.gasGovernor";
    }
  | {
      description: "Gas Holder";
      value: "commercial.utility.oilGas.gasHolder";
    }
  | {
      description: "Oil Terminal";
      value: "commercial.utility.oilGas.oilTerminal";
    }
  | {
      description: "Other Utility Use";
      value: "commercial.utility.other";
    }
  | {
      description: "Cable Terminal Station";
      value: "commercial.utility.other.cableTerminal";
    }
  | {
      description: "Observatory";
      value: "commercial.utility.other.observatory";
    }
  | {
      description: "Radar Station";
      value: "commercial.utility.other.radar";
    }
  | {
      description: "Satellite Earth Station";
      value: "commercial.utility.other.satelliteEarth";
    }
  | {
      description: "Telephone Box";
      value: "commercial.utility.publicPhone.box";
    }
  | {
      description: "Other Public Telephones";
      value: "commercial.utility.publicPhone.other";
    }
  | {
      description: "Telecommunication";
      value: "commercial.utility.telecoms";
    }
  | {
      description: "Telephone Exchange";
      value: "commercial.utility.telecoms.exchange";
    }
  | {
      description: "Telecommunications Mast";
      value: "commercial.utility.telecoms.mast";
    }
  | {
      description: "Waste Management";
      value: "commercial.utility.wasteManagement";
    }
  | {
      description: "Pump House / Pumping Station / Water Tower";
      value: "commercial.utility.water";
    }
  | {
      description: "Flood control infrastructure";
      value: "commercial.utility.water.floodControl";
    }
  | {
      description: "Water Controlling / Pumping";
      value: "commercial.utility.water.pump.control";
    }
  | {
      description: "Water Distribution / Pumping";
      value: "commercial.utility.water.pump.distribution";
    }
  | {
      description: "Water Quality Monitoring";
      value: "commercial.utility.water.qualityMonitoring";
    }
  | {
      description: "Water Storage";
      value: "commercial.utility.water.storage";
    }
  | {
      description: "Water / Waste Water / Sewage Treatment Works";
      value: "commercial.utility.water.treatment";
    }
  | {
      description: "Waste Water Distribution / Pumping";
      value: "commercial.utility.water.waste";
    }
  | {
      description: "Waste Water Treatment";
      value: "commercial.utility.water.wasteTreatment";
    }
  | {
      description: "Water Treatment";
      value: "commercial.utility.water.waterTreatment";
    }
  | {
      description: "Dual Use";
      value: "dualUse";
    }
  | {
      description: "Land";
      value: "land";
    }
  | {
      description: "Allotment";
      value: "land.allotment";
    }
  | {
      description: "Amenity - Open areas not attracting visitors";
      value: "land.amenity";
    }
  | {
      description: "Verge / Central Reservation";
      value: "land.amenity.natural";
    }
  | {
      description: "Natural Central Reservation";
      value: "land.amenity.natural.centralReservation";
    }
  | {
      description: "Natural Verge";
      value: "land.amenity.natural.verge";
    }
  | {
      description: "Landscaped Roundabout";
      value: "land.amenity.roundabout";
    }
  | {
      description: "Maintained Amenity Land";
      value: "land.amenity.surface";
    }
  | {
      description: "Made Central Reservation";
      value: "land.amenity.surface.centralReservation";
    }
  | {
      description: "Pavement";
      value: "land.amenity.surface.pavement";
    }
  | {
      description: "Aviation operational land";
      value: "land.aviation";
    }
  | {
      description: "Burial Ground";
      value: "land.burial";
    }
  | {
      description: "Historic / Disused Cemetery / Graveyard";
      value: "land.burial.historic";
    }
  | {
      description: "Development";
      value: "land.development";
    }
  | {
      description: "Development Site";
      value: "land.development.construction";
    }
  | {
      description: "Commercial Construction Site";
      value: "land.development.construction.commercial";
    }
  | {
      description: "Community Construction Site";
      value: "land.development.construction.community";
    }
  | {
      description: "Residential Construction Site";
      value: "land.development.construction.residential";
    }
  | {
      description: "Transport Construction Site";
      value: "land.development.construction.transport";
    }
  | {
      description: "Forestry";
      value: "land.forest";
    }
  | {
      description: "Arboretum";
      value: "land.forest.arboretum";
    }
  | {
      description: "Woodland";
      value: "land.forest.woods";
    }
  | {
      description: "Land within boundaries of a road";
      value: "land.highways";
    }
  | {
      description: "Industrial land";
      value: "land.industrial";
    }
  | {
      description: "Open Space";
      value: "land.open";
    }
  | {
      description: "Heath / Moorland";
      value: "land.open.moor";
    }
  | {
      description: "Park";
      value: "land.park";
    }
  | {
      description: "Public Open Space / Nature Reserve";
      value: "land.park.natureReserve";
    }
  | {
      description: "Playground";
      value: "land.park.play";
    }
  | {
      description: "Paddling Pool";
      value: "land.park.play.paddlingPool";
    }
  | {
      description: "Play Area";
      value: "land.park.play.playground";
    }
  | {
      description: "Private Park / Garden";
      value: "land.park.private";
    }
  | {
      description: "Public Park / Garden";
      value: "land.park.public";
    }
  | {
      description: "Smallholding";
      value: "land.smallholding";
    }
  | {
      description: "Unused Land";
      value: "land.unused";
    }
  | {
      description: "Vacant land / derelict building";
      value: "land.unused.vacant";
    }
  | {
      description: "Water";
      value: "land.water";
    }
  | {
      description: "Named Pond";
      value: "land.water.pond";
    }
  | {
      description: "Decoy Pond";
      value: "land.water.pond.decoy";
    }
  | {
      description: "Dew Pond";
      value: "land.water.pond.dew";
    }
  | {
      description: "Static Water";
      value: "land.water.pond.static";
    }
  | {
      description: "Lake / Reservoir";
      value: "land.water.reservoir";
    }
  | {
      description: "Buried Reservoir";
      value: "land.water.reservoir.buried";
    }
  | {
      description: "Balancing Pond";
      value: "land.water.reservoir.pond";
    }
  | {
      description: "Waterway";
      value: "land.water.way";
    }
  | {
      description: "Drain";
      value: "land.water.way.drain";
    }
  | {
      description: "Leats / Races";
      value: "land.water.way.leatsRaces";
    }
  | {
      description: "Military";
      value: "military";
    }
  | {
      description: "Air Force";
      value: "military.airForce";
    }
  | {
      description: "Air Force Military Range";
      value: "military.airForce.range";
    }
  | {
      description: "Air Force Site";
      value: "military.airForce.site";
    }
  | {
      description: "Air Force Military Storage";
      value: "military.airForce.storage";
    }
  | {
      description: "Air Force Military Training";
      value: "military.airForce.training";
    }
  | {
      description: "Army";
      value: "military.army";
    }
  | {
      description: "Army Military Range";
      value: "military.army.range";
    }
  | {
      description: "Army Site";
      value: "military.army.site";
    }
  | {
      description: "Army Military Storage";
      value: "military.army.storage";
    }
  | {
      description: "Army Military Training";
      value: "military.army.training";
    }
  | {
      description: "Military Barracks";
      value: "military.barracks";
    }
  | {
      description: "Ancillary Building";
      value: "military.building";
    }
  | {
      description: "Military Target";
      value: "military.building.target";
    }
  | {
      description: "Defence Estates";
      value: "military.defenceEstates";
    }
  | {
      description: "Navy";
      value: "military.navy";
    }
  | {
      description: "Naval Military Range";
      value: "military.navy.range";
    }
  | {
      description: "Naval Site";
      value: "military.navy.site";
    }
  | {
      description: "Naval Military Storage";
      value: "military.navy.storage";
    }
  | {
      description: "Naval Military Training";
      value: "military.navy.training";
    }
  | {
      description: "Mixed use (within single planning unit)";
      value: "mixedUse";
    }
  | {
      description: "Object of Interest";
      value: "object";
    }
  | {
      description: "Archaeological Dig Site";
      value: "object.archaeological";
    }
  | {
      description: "Monument";
      value: "object.monument";
    }
  | {
      description: "Memorial / Market Cross";
      value: "object.monument.memorial";
    }
  | {
      description: "Other Structure";
      value: "object.monument.other";
    }
  | {
      description: "Permanent Art Display / Sculpture";
      value: "object.monument.other.art";
    }
  | {
      description: "Boundary Stone";
      value: "object.monument.other.boundaryStone";
    }
  | {
      description: "Cascade / Fountain";
      value: "object.monument.other.waterFeature";
    }
  | {
      description: "Windmill (Inactive)";
      value: "object.monument.other.windmill";
    }
  | {
      description: "Castle / Historic Ruin";
      value: "object.monument.ruin";
    }
  | {
      description: "Statue";
      value: "object.monument.statue";
    }
  | {
      description: "Obelisk / Milestone / Standing Stone";
      value: "object.monument.vertical";
    }
  | {
      description: "Obelisk";
      value: "object.monument.vertical.obelisk";
    }
  | {
      description: "Standing Stone";
      value: "object.monument.vertical.standingStone";
    }
  | {
      description: "Place Of Worship";
      value: "object.religious";
    }
  | {
      description: "Religious building";
      value: "object.religious.building";
    }
  | {
      description: "Abbey";
      value: "object.religious.building.abbey";
    }
  | {
      description: "Cathedral";
      value: "object.religious.building.cathedral";
    }
  | {
      description: "Chapel";
      value: "object.religious.building.chapel";
    }
  | {
      description: "Church";
      value: "object.religious.building.church";
    }
  | {
      description: "Gurdwara";
      value: "object.religious.building.gurdwara";
    }
  | {
      description: "Kingdom Hall";
      value: "object.religious.building.kingdomHall";
    }
  | {
      description: "Lych Gate";
      value: "object.religious.building.lychGate";
    }
  | {
      description: "Minster";
      value: "object.religious.building.minster";
    }
  | {
      description: "Mosque";
      value: "object.religious.building.mosque";
    }
  | {
      description: "Stupa";
      value: "object.religious.building.stupa";
    }
  | {
      description: "Synagogue";
      value: "object.religious.building.synagogue";
    }
  | {
      description: "Temple";
      value: "object.religious.building.temple";
    }
  | {
      description: "Stately Home";
      value: "object.statelyHome";
    }
  | {
      description: "Underground Feature";
      value: "object.underground";
    }
  | {
      description: "Cave";
      value: "object.underground.cave";
    }
  | {
      description: "Pothole / Natural Hole";
      value: "object.underground.hole";
    }
  | {
      description: "Other Underground Feature";
      value: "object.underground.other";
    }
  | {
      description: "Cellar";
      value: "object.underground.other.cellar";
    }
  | {
      description: "Disused Mine";
      value: "object.underground.other.extraction";
    }
  | {
      description: "Mineral Mining / Inactive";
      value: "object.underground.other.extraction.mine";
    }
  | {
      description: "Oil And / Gas Extraction/ Inactive";
      value: "object.underground.other.extraction.oilGas";
    }
  | {
      description: "Mineral Quarrying And / Open Extraction / Inactive";
      value: "object.underground.other.extraction.quarry";
    }
  | {
      description: "Well / Spring";
      value: "object.underground.other.water";
    }
  | {
      description: "Spring";
      value: "object.underground.other.water.spring";
    }
  | {
      description: "Well";
      value: "object.underground.other.water.well";
    }
  | {
      description: "Other (Ordnance Survey only)";
      value: "other";
    }
  | {
      description: "Agricultural Support Objects";
      value: "other.agriculture";
    }
  | {
      description: "Currick";
      value: "other.agriculture.currick";
    }
  | {
      description: "Fish Ladder / Lock / Pen / Trap";
      value: "other.agriculture.fishPen";
    }
  | {
      description: "Livestock Pen / Dip";
      value: "other.agriculture.livestockPen";
    }
  | {
      description: "Slurry Bed / Pit";
      value: "other.agriculture.slurry";
    }
  | {
      description: "Ancillary Building";
      value: "other.ancillary";
    }
  | {
      description: "Aviary / Dovecot / Cage";
      value: "other.ancillary.aviary";
    }
  | {
      description: "Bandstand";
      value: "other.ancillary.bandstand";
    }
  | {
      description: "Pavilion / Changing Room";
      value: "other.ancillary.pavilion";
    }
  | {
      description: "Sports Viewing Structure";
      value: "other.ancillary.sportsViewing";
    }
  | {
      description: "Coastal Protection / Flood Prevention";
      value: "other.coastal";
    }
  | {
      description: "Flood Gate / Flood Sluice Gate / Flood Valve";
      value: "other.coastal.floodGate";
    }
  | {
      description: "Groyne";
      value: "other.coastal.groyne";
    }
  | {
      description: "Rip-Rap";
      value: "other.coastal.ripRap";
    }
  | {
      description: "Boulder Wall / Sea Wall";
      value: "other.coastal.wall";
    }
  | {
      description: "Emergency Support";
      value: "other.emergency";
    }
  | {
      description: "Fire Alarm Structure / Fire Observation Tower / Fire Beater Facility";
      value: "other.emergency.fire";
    }
  | {
      description: "Beach Office / First Aid Facility";
      value: "other.emergency.firstAid";
    }
  | {
      description: "LIfe / Belt / Buoy / Float / Jacket / Safety Rope";
      value: "other.emergency.floatAids";
    }
  | {
      description: "Emergency Telephone (Non Motorway)";
      value: "other.emergency.telephone";
    }
  | {
      description: "Emergency Equipment Point / Emergency Siren / Warning Flag";
      value: "other.emergency.warning";
    }
  | {
      description: "Historical Site / Object";
      value: "other.historic";
    }
  | {
      description: "Historic Structure / Object";
      value: "other.historic.structure";
    }
  | {
      description: "Industrial Support";
      value: "other.industrial";
    }
  | {
      description: "Adit / Incline / Level";
      value: "other.industrial.aditIncline";
    }
  | {
      description: "Caisson / Dry Dock / Grid";
      value: "other.industrial.caissonDock";
    }
  | {
      description: "Channel / Conveyor / Conduit / Pipe";
      value: "other.industrial.channel";
    }
  | {
      description: "Chimney / Flue";
      value: "other.industrial.chimney";
    }
  | {
      description: "Cooling Tower";
      value: "other.industrial.coolingTower";
    }
  | {
      description: "Crane / Hoist / Winch / Material Elevator";
      value: "other.industrial.crane";
    }
  | {
      description: "Grab / Skip / Other Industrial Waste Machinery / Discharging";
      value: "other.industrial.discharge";
    }
  | {
      description: "Flare Stack";
      value: "other.industrial.flareStack";
    }
  | {
      description: "Kiln / Oven / Smelter";
      value: "other.industrial.kiln";
    }
  | {
      description: "Manhole / Shaft";
      value: "other.industrial.manholeShaft";
    }
  | {
      description: "Industrial Overflow / Sluice / Valve / Valve Housing";
      value: "other.industrial.overflowSluiceValve";
    }
  | {
      description: "Electricity Distribution Pole / Pylon";
      value: "other.industrial.pylon.electricity";
    }
  | {
      description: "Telephone Pole / Post";
      value: "other.industrial.pylon.telecom";
    }
  | {
      description: "Hopper / Silo / Cistern / Tank";
      value: "other.industrial.siloTank";
    }
  | {
      description: "Solar Panel / Waterwheel";
      value: "other.industrial.solarPanel";
    }
  | {
      description: "Information";
      value: "other.information";
    }
  | {
      description: "Advertising Hoarding";
      value: "other.information.advertising";
    }
  | {
      description: "Tourist Information Signage";
      value: "other.information.touristSign";
    }
  | {
      description: "Traffic Information Signage";
      value: "other.information.trafficSign";
    }
  | {
      description: "Sport / Leisure Support";
      value: "other.leisure";
    }
  | {
      description: "Gallop / Ride";
      value: "other.leisure.gallop";
    }
  | {
      description: "Butt / Hide";
      value: "other.leisure.hide";
    }
  | {
      description: "Miniature Railway";
      value: "other.leisure.modelRailway";
    }
  | {
      description: "Royal Mail Infrastructure";
      value: "other.mail";
    }
  | {
      description: "PO Box";
      value: "other.mail.POBox";
    }
  | {
      description: "Additional Mail / Packet Addressee";
      value: "other.mail.additionalAddressee";
    }
  | {
      description: "Postal Delivery Box / Pouch";
      value: "other.mail.deliveryBox";
    }
  | {
      description: "Postal Box";
      value: "other.mail.postBox";
    }
  | {
      description: "Significant Natural Object";
      value: "other.natural";
    }
  | {
      description: "Natural Hole (Blow / Shake / Swallow)";
      value: "other.natural.hole";
    }
  | {
      description: "Boundary / Significant Rock / Boulder";
      value: "other.natural.rock";
    }
  | {
      description: "Boundary / Significant / Historic Tree / Pollard";
      value: "other.natural.tree";
    }
  | {
      description: "Aid To Navigation";
      value: "other.navigation";
    }
  | {
      description: "Aid To Aeronautical Navigation";
      value: "other.navigation.air";
    }
  | {
      description: "Aeronautical Navigation Beacon / Light";
      value: "other.navigation.air.beacon";
    }
  | {
      description: "Landing Light";
      value: "other.navigation.air.landingLight";
    }
  | {
      description: "Signal Square";
      value: "other.navigation.air.signalSquare";
    }
  | {
      description: "Wind Sock / Wind Tee";
      value: "other.navigation.air.windSock";
    }
  | {
      description: "Guide Post";
      value: "other.navigation.guidePost";
    }
  | {
      description: "Aid To Nautical Navigation";
      value: "other.navigation.nautical";
    }
  | {
      description: "Nautical Navigation Beacon / Light";
      value: "other.navigation.nautical.beacon";
    }
  | {
      description: "Daymark";
      value: "other.navigation.nautical.daymark";
    }
  | {
      description: "Fog Horn Warning";
      value: "other.navigation.nautical.fogHorn";
    }
  | {
      description: "Aid To Road Navigation";
      value: "other.navigation.road";
    }
  | {
      description: "Ornamental / Cultural Object";
      value: "other.ornamental";
    }
  | {
      description: "Maze";
      value: "other.ornamental.maze";
    }
  | {
      description: "Simple Ornamental Object";
      value: "other.ornamental.object";
    }
  | {
      description: "Mausoleum / Tomb / Grave";
      value: "other.ornamental.tomb";
    }
  | {
      description: "Scientific / Observation Support";
      value: "other.scientific";
    }
  | {
      description: "Telescope / Observation Infrastructure / Astronomy";
      value: "other.scientific.astronomy";
    }
  | {
      description: "Meteorological Station / Equipment";
      value: "other.scientific.meteo";
    }
  | {
      description: "Radar / Satellite Infrastructure";
      value: "other.scientific.radarSatellite";
    }
  | {
      description: "Street Furniture";
      value: "other.streetFurniture";
    }
  | {
      description: "Transport Support";
      value: "other.transport";
    }
  | {
      description: "Footbridge / Walkway";
      value: "other.transport.bridge";
    }
  | {
      description: "Cattle Grid / Ford";
      value: "other.transport.cattleGridFord";
    }
  | {
      description: "Customs Inspection Facility";
      value: "other.transport.customs";
    }
  | {
      description: "Goods Tramway";
      value: "other.transport.goodsTramway";
    }
  | {
      description: "Lay-By";
      value: "other.transport.layby";
    }
  | {
      description: "Mail Pick Up";
      value: "other.transport.mailPickUp";
    }
  | {
      description: "Pole / Post / Bollard (Restricting Vehicular Access)";
      value: "other.transport.post";
    }
  | {
      description: "Railway Buffer";
      value: "other.transport.rail.buffer";
    }
  | {
      description: "Railway Pedestrian Crossing";
      value: "other.transport.rail.crossing.pedestrian";
    }
  | {
      description: "Level Crossing";
      value: "other.transport.rail.crossing.vehicles";
    }
  | {
      description: "Rail Drag";
      value: "other.transport.rail.drag";
    }
  | {
      description: "Rail Infrastructure Services";
      value: "other.transport.rail.infrastructure";
    }
  | {
      description: "Railway Lighting";
      value: "other.transport.rail.lighting";
    }
  | {
      description: "Rail Kilometre Distance Marker";
      value: "other.transport.rail.marker.km";
    }
  | {
      description: "Rail Mile Distance Marker";
      value: "other.transport.rail.market.mile";
    }
  | {
      description: "Rail Signalling";
      value: "other.transport.rail.signals";
    }
  | {
      description: "Railway Traverse";
      value: "other.transport.rail.traverse";
    }
  | {
      description: "Railway Turntable";
      value: "other.transport.rail.turntable";
    }
  | {
      description: "Rail Weighbridge";
      value: "other.transport.rail.weighbridge";
    }
  | {
      description: "Road Drag";
      value: "other.transport.road.drag";
    }
  | {
      description: "Road Infrastructure Services";
      value: "other.transport.road.infrastructure";
    }
  | {
      description: "Road Mile Distance Marker";
      value: "other.transport.road.marker.mile";
    }
  | {
      description: "Road Kilometre Distance Marker";
      value: "other.transport.road.market.km";
    }
  | {
      description: "Road Turntable";
      value: "other.transport.road.turntable";
    }
  | {
      description: "Vehicle Dip";
      value: "other.transport.road.vehicleDip";
    }
  | {
      description: "Elevator / Escalator / Steps";
      value: "other.transport.stepsLiftEscalator";
    }
  | {
      description: "Subway / Underpass";
      value: "other.transport.subway";
    }
  | {
      description: "Unsupported Site";
      value: "other.unsupported";
    }
  | {
      description: "Cycle Parking Facility";
      value: "other.unsupported.cycleParking";
    }
  | {
      description: "Picnic / Barbeque Site";
      value: "other.unsupported.picnic";
    }
  | {
      description: "Shelter (Not Including Bus Shelter)";
      value: "other.unsupported.shelter";
    }
  | {
      description: "Travelling Persons Site";
      value: "other.unsupported.travellingPersons";
    }
  | {
      description: "Parent Shell";
      value: "parent";
    }
  | {
      description: "Property Shell";
      value: "parent.property";
    }
  | {
      description: "Street Record";
      value: "parent.street";
    }
  | {
      description: "Residential";
      value: "residential";
    }
  | {
      description: "Ancillary Building";
      value: "residential.ancillary";
    }
  | {
      description: "House Boat";
      value: "residential.boat";
    }
  | {
      description: "Car Park Space";
      value: "residential.carParkingSpace";
    }
  | {
      description: "Allocated Parking";
      value: "residential.carParkingSpace.allocated";
    }
  | {
      description: "Caravan";
      value: "residential.caravan";
    }
  | {
      description: "Children’s home";
      value: "residential.childrensHome";
    }
  | {
      description: "Extra care housing";
      value: "residential.extraCareHousing";
    }
  | {
      description: "Flat";
      value: "residential.flat";
    }
  | {
      description: "Garage";
      value: "residential.garage";
    }
  | {
      description: "Privately Owned Holiday Caravan / Chalet";
      value: "residential.holiday";
    }
  | {
      description: "House In Multiple Occupation";
      value: "residential.HMO";
    }
  | {
      description: "HMO Bedsit / Other Non Self Contained Accommodation";
      value: "residential.HMO.bedsit";
    }
  | {
      description: "HMO Parent";
      value: "residential.HMO.parent";
    }
  | {
      description: "HMO Not Further Divided";
      value: "residential.HMO.undivided";
    }
  | {
      description: "House";
      value: "residential.house";
    }
  | {
      description: "Detached";
      value: "residential.house.detached";
    }
  | {
      description: "Semi-detached";
      value: "residential.house.semiDetached";
    }
  | {
      description: "Terrace";
      value: "residential.house.terrace";
    }
  | {
      description: "Residential Institution";
      value: "residential.institution";
    }
  | {
      description: "Care / Nursing Home";
      value: "residential.institution.care";
    }
  | {
      description: "Communal Residence";
      value: "residential.institution.communal";
    }
  | {
      description: "Residential Education";
      value: "residential.institution.education";
    }
  | {
      description: "Non-Commercial Lodgings";
      value: "residential.institution.noncommercial";
    }
  | {
      description: "Religious Community";
      value: "residential.institution.religious";
    }
  | {
      description: "Mobile home";
      value: "residential.mobileHome";
    }
  | {
      description: "Multiple residential units";
      value: "residential.multiple";
    }
  | {
      description: "Park home";
      value: "residential.parkHome";
    }
  | {
      description: "Serviced accommodation";
      value: "residential.serviced";
    }
  | {
      description: "Sheltered Accommodation";
      value: "residential.shelteredAccommodation";
    }
  | {
      description: "Unclassified";
      value: "unclassified";
    }
  | {
      description: "Awaiting Classification";
      value: "unclassified.awaitingclassification";
    }
  | {
      description: "Pending Internal Investigation";
      value: "unclassified.pendingInvestigation";
    };
export type Date = string;
/**
 * Planning breach types
 */
export type BreachType =
  | {
      description: "Alteration";
      value: "alter";
    }
  | {
      description: "New or modified boundary fence or wall";
      value: "alter.boundary";
    }
  | {
      description: "Microwave antennas or satellite dishes";
      value: "alter.equipment.antennae";
    }
  | {
      description: "Creation of a new access (eg a dropped kerb)";
      value: "alter.highways";
    }
  | {
      description: "Change of land levels";
      value: "alter.landscape";
    }
  | {
      description: "Works to windows or doors";
      value: "alter.openings";
    }
  | {
      description: "Changes to roof including skylights";
      value: "alter.roof";
    }
  | {
      description: "Chimney flue or soil and vent pipes";
      value: "alter.soilPipes";
    }
  | {
      description: "Creation of driveway or laying of hardstanding";
      value: "alter.surfaces.parking";
    }
  | {
      description: "New or modified swimming pool";
      value: "alter.swimmingPool";
    }
  | {
      description: "Works to trees";
      value: "alter.trees";
    }
  | {
      description: "Works to a dangerous or dead tree";
      value: "alter.trees.tree";
    }
  | {
      description: "Other works to a tree";
      value: "alter.trees.tree.other";
    }
  | {
      description: "Works to a healthy tree";
      value: "alter.trees.tree.prune";
    }
  | {
      description: "Felling of a tree";
      value: "alter.trees.tree.remove";
    }
  | {
      description: "Unauthorised change of use";
      value: "changeOfUse";
    }
  | {
      description: "Caravan or mobile homes";
      value: "changeOfUse.caravans";
    }
  | {
      description: "Extension";
      value: "extend";
    }
  | {
      description: "New or modified porch";
      value: "extend.porch";
    }
  | {
      description: "Inserting a dormer window";
      value: "extend.roof.dormer";
    }
  | {
      description: "Works to a listed building";
      value: "listed";
    }
  | {
      description: "Minerals and waste development";
      value: "minerals";
    }
  | {
      description: "Other type of planning breach";
      value: "other";
    }
  | {
      description: "New or modified outbuilding (eg garage or shed)";
      value: "outbuilding";
    }
  | {
      description: "Breach of a planning condition";
      value: "planningCondition";
    }
  | {
      description: "New adverts or signage (including flags)";
      value: "signage";
    }
  | {
      description: "Untidy land";
      value: "untidySite";
    };
/**
 * Types of planning documents and drawings
 */
export type FileType =
  | {
      description: "Details of impact on access, roads, and rights of way";
      value: "accessRoadsRightsOfWayDetails";
    }
  | {
      description: "Affordable housing statement";
      value: "affordableHousingStatement";
    }
  | {
      description: "Arboriculturist report";
      value: "arboriculturistReport";
    }
  | {
      description: "Bank statement";
      value: "bankStatement";
    }
  | {
      description: "Basement impact statement";
      value: "basementImpactStatement";
    }
  | {
      description: "Bio-aerosol assessment";
      value: "bioaerosolAssessment";
    }
  | {
      description: "Biodiversity Net Gain (BNG) information";
      value: "biodiversityNetGainInformation";
    }
  | {
      description: "Birdstrike risk management plan";
      value: "birdstrikeRiskManagementPlan";
    }
  | {
      description: "Borehole or trial pit analysis";
      value: "boreholeOrTrialPitAnalysis";
    }
  | {
      description: "Building control certificate";
      value: "buildingControlCertificate";
    }
  | {
      description: "Structural or building condition survey";
      value: "conditionSurvey";
    }
  | {
      description: "Construction invoice";
      value: "constructionInvoice";
    }
  | {
      description: "Contamination report";
      value: "contaminationReport";
    }
  | {
      description: "Council tax bill";
      value: "councilTaxBill";
    }
  | {
      description: "Crime prevention strategy";
      value: "crimePreventionStrategy";
    }
  | {
      description: "Design and Access Statement";
      value: "designAndAccessStatement";
    }
  | {
      description: "Evidence for application fee exemption - disability";
      value: "disabilityExemptionEvidence";
    }
  | {
      description: "Ecology report";
      value: "ecologyReport";
    }
  | {
      description: "Elevations - existing";
      value: "elevations.existing";
    }
  | {
      description: "Elevations - proposed";
      value: "elevations.proposed";
    }
  | {
      description: "Scheme for mitigation and monitoring of emissions (dust, odour and vibrations)";
      value: "emissionsMitigationAndMonitoringScheme";
    }
  | {
      description: "Energy statement";
      value: "energyStatement";
    }
  | {
      description: "Environmental Impact Assessment (EIA)";
      value: "environmentalImpactAssessment";
    }
  | {
      description: "External materials details";
      value: "externalMaterialsDetails";
    }
  | {
      description: "Fire safety report";
      value: "fireSafetyReport";
    }
  | {
      description: "Flood risk assessment (FRA)";
      value: "floodRiskAssessment";
    }
  | {
      description: "Floor plan - existing";
      value: "floorPlan.existing";
    }
  | {
      description: "Floor plan - proposed";
      value: "floorPlan.proposed";
    }
  | {
      description: "Foul drainage assessment";
      value: "foulDrainageAssessment";
    }
  | {
      description: "Geodiversity assessment";
      value: "geodiversityAssessment";
    }
  | {
      description: "Plans showing the stretches of hedgerows to be removed";
      value: "hedgerowsInformation";
    }
  | {
      description: "Evidence of the date of planting of the removed hedgerows";
      value: "hedgerowsInformation.plantingDate";
    }
  | {
      description: "Heritage Statement";
      value: "heritageStatement";
    }
  | {
      description: "Hydrological and hydrogeological assessment";
      value: "hydrologicalAssessment";
    }
  | {
      description: "Hydrology report";
      value: "hydrologyReport";
    }
  | {
      description: "Internal elevations";
      value: "internalElevations";
    }
  | {
      description: "Internal sections";
      value: "internalSections";
    }
  | {
      description: "Joiner's report";
      value: "joinersReport";
    }
  | {
      description: "Joinery section report";
      value: "joinerySections";
    }
  | {
      description: "Land contamination assessment";
      value: "landContaminationAssessment";
    }
  | {
      description: "Landscape and visual impact assessment (LVIA)";
      value: "landscapeAndVisualImpactAssessment";
    }
  | {
      description: "Landscape strategy or landscape plan";
      value: "landscapeStrategy";
    }
  | {
      description: "Lighting assessment";
      value: "lightingAssessment";
    }
  | {
      description: "Details of litter, vermin and bird control";
      value: "litterVerminAndBirdControlDetails";
    }
  | {
      description: "Location plan";
      value: "locationPlan";
    }
  | {
      description: "Method statement";
      value: "methodStatement";
    }
  | {
      description: "Minerals and waste assessment";
      value: "mineralsAndWasteAssessment";
    }
  | {
      description: "Information the authority considers necessary for the application";
      value: "necessaryInformation";
    }
  | {
      description: "New dwellings schedule";
      value: "newDwellingsSchedule";
    }
  | {
      description: "Noise assessment";
      value: "noiseAssessment";
    }
  | {
      description: "Open space assessment";
      value: "openSpaceAssessment";
    }
  | {
      description: "Other - document";
      value: "otherDocument";
    }
  | {
      description: "Other - drawing";
      value: "otherDrawing";
    }
  | {
      description: "Other - evidence or correspondence";
      value: "otherEvidence";
    }
  | {
      description: "Other - supporting document";
      value: "otherSupporting";
    }
  | {
      description: "Parking plan";
      value: "parkingPlan";
    }
  | {
      description: "Photographs - existing";
      value: "photographs.existing";
    }
  | {
      description: "Photographs - proposed";
      value: "photographs.proposed";
    }
  | {
      description: "Planning statement";
      value: "planningStatement";
    }
  | {
      description: "Recyclable waste storage details";
      value: "recycleWasteStorageDetails";
    }
  | {
      description: "Information the applicant considers relevant to the application";
      value: "relevantInformation";
    }
  | {
      description: "Residential units details";
      value: "residentialUnitsDetails";
    }
  | {
      description: "Roof plan - existing";
      value: "roofPlan.existing";
    }
  | {
      description: "Roof plan - proposed";
      value: "roofPlan.proposed";
    }
  | {
      description: "Sections - existing";
      value: "sections.existing";
    }
  | {
      description: "Sections - proposed";
      value: "sections.proposed";
    }
  | {
      description: "Site plan - existing";
      value: "sitePlan.existing";
    }
  | {
      description: "Site plan - proposed";
      value: "sitePlan.proposed";
    }
  | {
      description: "Sketch plan";
      value: "sketchPlan";
    }
  | {
      description: "Statement of community involvement";
      value: "statementOfCommunityInvolvement";
    }
  | {
      description: "Statutory declaration";
      value: "statutoryDeclaration";
    }
  | {
      description: "Details of storage treatment or disposal of waste";
      value: "storageTreatmentAndWasteDisposalDetails";
    }
  | {
      description: "Street scene drawing";
      value: "streetScene";
    }
  | {
      description: "Subsidence report";
      value: "subsidenceReport";
    }
  | {
      description: "Sunlight and daylight report";
      value: "sunlightAndDaylightReport";
    }
  | {
      description: "Sustainability statement";
      value: "sustainabilityStatement";
    }
  | {
      description: "Technical evidence";
      value: "technicalEvidence";
    }
  | {
      description: "Technical specification";
      value: "technicalSpecification";
    }
  | {
      description: "Tenancy agreement";
      value: "tenancyAgreement";
    }
  | {
      description: "Tenancy invoice";
      value: "tenancyInvoice";
    }
  | {
      description: "Town centre uses - Impact assessment";
      value: "townCentreImpactAssessment";
    }
  | {
      description: "Town centre uses - Sequential assessment";
      value: "townCentreSequentialAssessment";
    }
  | {
      description: "Transport assessment";
      value: "transportAssessment";
    }
  | {
      description: "Travel plan";
      value: "travelPlan";
    }
  | {
      description: "Location of trees and hedges";
      value: "treeAndHedgeLocation";
    }
  | {
      description: "Removed or pruned trees and hedges";
      value: "treeAndHedgeRemovedOrPruned";
    }
  | {
      description: "Tree canopy calculator";
      value: "treeCanopyCalculator";
    }
  | {
      description: "Tree condition report";
      value: "treeConditionReport";
    }
  | {
      description: "Trees report";
      value: "treesReport";
    }
  | {
      description: "Tree survey";
      value: "treeSurvey";
    }
  | {
      description: "Unit plan - existing";
      value: "unitPlan.existing";
    }
  | {
      description: "Unit plan - proposed";
      value: "unitPlan.proposed";
    }
  | {
      description: "Use plan - existing";
      value: "usePlan.existing";
    }
  | {
      description: "Use plan - proposed";
      value: "usePlan.proposed";
    }
  | {
      description: "Utility bill";
      value: "utilityBill";
    }
  | {
      description: "Utilities statement";
      value: "utilitiesStatement";
    }
  | {
      description: "Ventilation or extraction statement";
      value: "ventilationStatement";
    }
  | {
      description: "Viability Appraisal";
      value: "viabilityAppraisal";
    }
  | {
      description: "Visualisations";
      value: "visualisations";
    }
  | {
      description: "Waste and recycling strategy";
      value: "wasteAndRecyclingStrategy";
    }
  | {
      description: "Waste storage details";
      value: "wasteStorageDetails";
    }
  | {
      description: "Water environment assessment";
      value: "waterEnvironmentAssessment";
    };
export type URL = string;
export type UUID = string;
/**
 * Regex-based implementation of iso-date-time until available in ajv-formats@3.0.0
 */
export type DateTime = string;
/**
 * The ordered list of questions, answers, and their metadata for the application
 */
export type Responses = QuestionAndResponses[];

/**
 * The root specification for an enforcement report in England generated by a digital planning service
 */
export interface Enforcement {
  data: {
    application: {
      type: {
        description: "Report a planning breach";
        value: "breach";
      };
    };
    complainant: Complainant;
    /**
     * Details of the site
     */
    property: {
      /**
       * The property address
       */
      address: ProposedSiteAddress | OSSiteAddress;
      boundary?: GeoBoundary;
      /**
       * Current and historic UK Local Authority Districts that contain this address sourced from planning.data.gov.uk/dataset/local-authority-district
       */
      localAuthorityDistrict: string[];
      region: Region;
      type: PropertyType;
      /**
       * Name of the ward sourced from planning.data.gov.uk/dataset/ward
       */
      ward: string;
    };
    /**
     * Details of the enforcement report
     */
    report: {
      boundary?: GeoBoundary1;
      /**
       * Start and end date of the enforcement breach if applicable; ongoing breaches will not have an end date
       */
      date?: {
        end?: Date;
        start: Date;
      };
      /**
       * Description of the enforcement breach
       */
      description?: string;
      /**
       * Categorical type of enforcement breach
       */
      projectType?: (
        | BreachType
        | {
            description?: string;
            value: string;
          }
      )[];
    };
  };
  files?: File[];
  metadata: PlanXMetadata;
  responses: Responses;
}
/**
 * Contact details for the complainant filing the enforcement report
 */
export interface Complainant {
  address: ContactAddress;
  company?: {
    name: string;
  };
  email: Email;
  name: {
    first: string;
    last: string;
    title?: string;
  };
  phone: {
    primary: string;
  };
}
/**
 * Address information for a person associated with this application not at the site address
 */
export interface ContactAddress {
  country?: string;
  county?: string;
  line1: string;
  line2?: string;
  postcode: string;
  town: string;
}
/**
 * Address information for sites without a known Unique Property Reference Number (UPRN)
 */
export interface ProposedSiteAddress {
  /**
   * Latitude coordinate in EPSG:4326 (WGS84)
   */
  latitude: number;
  /**
   * Longitude coordinate in EPSG:4326 (WGS84)
   */
  longitude: number;
  source: "Proposed by applicant";
  /**
   * Single line address description
   */
  title: string;
  /**
   * Easting coordinate in British National Grid (OSGB36)
   */
  x: number;
  /**
   * Northing coordinate in British National Grid (OSGB36)
   */
  y: number;
}
/**
 * Address information for sites with a known address sourced from Ordnance Survey AddressBase Premium LPI source
 */
export interface OSSiteAddress {
  /**
   * Latitude coordinate in EPSG:4326 (WGS84)
   */
  latitude: number;
  /**
   * Longitude coordinate in EPSG:4326 (WGS84)
   */
  longitude: number;
  organisation?: string;
  pao: PrimaryAddressableObjectPAOStartRangeAndOrBuildingDescription;
  paoEnd?: PrimaryAddressableObjectPAOEndRange;
  postcode: string;
  sao?: SecondaryAddressableObjectSAOStartRangeAndOrBuildingDescription;
  saoEnd?: SecondaryAddressableObjectSAOEndRange;
  singleLine: string;
  source: "Ordnance Survey";
  street: string;
  /**
   * Single line address description
   */
  title: string;
  town: string;
  uprn: UniquePropertyReferenceNumber;
  usrn: UniqueStreetReferenceNumber;
  /**
   * Easting coordinate in British National Grid (OSGB36)
   */
  x: number;
  /**
   * Northing coordinate in British National Grid (OSGB36)
   */
  y: number;
}
/**
 * HM Land Registry Index polygon for this property, commonly referred to as the blue line boundary, sourced from planning.data.gov.uk/dataset/title-boundary
 */
export interface GeoBoundary {
  area: Area;
  site: GeoJSON;
}
export interface Area {
  hectares?: number;
  squareMetres: number;
}
/**
 * Point geometry object. https://tools.ietf.org/html/rfc7946#section-3.1.2
 */
export interface Point {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position;
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "Point";
}
/**
 * MultiPoint geometry object.  https://tools.ietf.org/html/rfc7946#section-3.1.3
 */
export interface MultiPoint {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position[];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "MultiPoint";
}
/**
 * LineString geometry object. https://tools.ietf.org/html/rfc7946#section-3.1.4
 */
export interface LineString {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position[];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "LineString";
}
/**
 * MultiLineString geometry object. https://tools.ietf.org/html/rfc7946#section-3.1.5
 */
export interface MultiLineString {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position[][];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "MultiLineString";
}
/**
 * Polygon geometry object. https://tools.ietf.org/html/rfc7946#section-3.1.6
 */
export interface Polygon {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position[][];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "Polygon";
}
/**
 * MultiPolygon geometry object. https://tools.ietf.org/html/rfc7946#section-3.1.7
 */
export interface MultiPolygon {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  coordinates: Position[][][];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "MultiPolygon";
}
/**
 * Geometry Collection https://tools.ietf.org/html/rfc7946#section-3.1.8
 */
export interface GeometryCollection {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  geometries: Geometry[];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "GeometryCollection";
}
/**
 * A feature object which contains a geometry and associated properties. https://tools.ietf.org/html/rfc7946#section-3.2
 */
export interface Feature3CGeometry2CGeoJsonProperties3E {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  /**
   * The feature's geometry
   */
  geometry:
    | Point
    | MultiPoint
    | LineString
    | MultiLineString
    | Polygon
    | MultiPolygon
    | GeometryCollection;
  /**
   * A value that uniquely identifies this feature in a https://tools.ietf.org/html/rfc7946#section-3.2.
   */
  id?: string | number;
  /**
   * Properties associated with this feature.
   */
  properties: {
    [k: string]: unknown;
  } | null;
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "Feature";
}
/**
 * A collection of feature objects.  https://tools.ietf.org/html/rfc7946#section-3.3
 */
export interface FeatureCollection3CGeometry2CGeoJsonProperties3E {
  /**
   * Bounding box of the coordinate range of the object's Geometries, Features, or Feature Collections. The value of the bbox member is an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries. https://tools.ietf.org/html/rfc7946#section-5
   */
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number];
  features: Feature3CGeometry2CGeoJsonProperties3E[];
  /**
   * Specifies the type of GeoJSON object.
   */
  type: "FeatureCollection";
}
/**
 * Boundary of the enforcement breach if provided digitally
 */
export interface GeoBoundary1 {
  area: Area;
  site: GeoJSON;
}
/**
 * File uploaded and labeled by the user to support the application
 */
export interface File {
  description?: string;
  name: string;
  type: FileType[];
}
/**
 * Additional metadata associated with applications submitted via PlanX
 */
export interface PlanXMetadata {
  /**
   * Unique identifier for this application
   */
  id: string;
  /**
   * The reference code for the organisation responsible for processing this planning application, sourced from planning.data.gov.uk/dataset/local-authority
   */
  organisation: string;
  schema: URL;
  service: {
    fee: FeeExplanation | FeeExplanationNotApplicable;
    files: RequestedFiles;
    flowId: UUID;
    url: URL;
  };
  source: "PlanX";
  submittedAt: DateTime;
}
/**
 * An explanation, including policy references, of the fees associated with this application
 */
export interface FeeExplanation {
  calculated: CalculateMetadata[];
  /**
   * Breakdown of calculated fee by category of development, based on the scales defined in The Town and Country Planning Regulations https://www.legislation.gov.uk/uksi/2012/2920/schedule/1/part/2
   */
  category?: {
    eight?: CalculateMetadata[];
    eleven?: {
      one: CalculateMetadata[];
    };
    five?: CalculateMetadata[];
    four?: CalculateMetadata[];
    fourteen?: CalculateMetadata[];
    nine?: CalculateMetadata[];
    one?: CalculateMetadata[];
    sixAndSeven?: CalculateMetadata[];
    ten?: CalculateMetadata[];
    thirteen?: CalculateMetadata[];
    three?: CalculateMetadata[];
    twelve?: {
      one?: CalculateMetadata[];
      two?: CalculateMetadata[];
    };
    two?: CalculateMetadata[];
  };
  payable: CalculateMetadata[];
}
/**
 * Metadata associated with PlanX Calculate components used to determine fees throughout a service
 */
export interface CalculateMetadata {
  description?: string;
  policyRefs?: {
    text: string;
    url?: URL;
  }[];
}
/**
 * An indicator that an application fee does not apply to this application type or journey, therefore there is not an explanation of how it was calculated
 */
export interface FeeExplanationNotApplicable {
  notApplicable: true;
}
/**
 * File types requested by this service. Schema["files"] will be a subset of this list based on the user's journey through the service
 */
export interface RequestedFiles {
  optional: FileType[];
  recommended: FileType[];
  required: FileType[];
}
export interface QuestionAndResponses {
  metadata?: QuestionMetaData;
  question: string;
  responses: Response[] | string;
}
export interface QuestionMetaData {
  autoAnswered?: boolean;
  id?: string;
  policyRefs?: {
    text: string;
    url?: URL;
  }[];
  sectionName?: string;
  tags?: string[];
}
export interface Response {
  metadata?: ResponseMetaData;
  value: string;
}
export interface ResponseMetaData {
  flags?: string[];
  options?: string[] | Response[];
}
